[package]
name = "vmod_uap"
version = "0.0.1"
edition = "2021"
license = "BSD-3-Clause"

[build-dependencies]
varnish = "0.0.16"

[dependencies]
uaparser = "0.6.0"
varnish = "0.0.16"

[lib]
crate-type = ["cdylib"]
